let nom = "   Fatima   ";
let age = "23";
let email = "fatima@example";
let scoreJeu = "150pts";
let estAdmin = "false";
let derniereConnexion = null;
let nombreConnexions = "0";
let nomNettoye = nom.trim(); 
let ageNombre = parseInt(age, 10);
let emailValide = email.includes("@") && email.includes("."); 
let scoreJeuNombre = parseInt(scoreJeu, 10); 
let estAdminBool = (estAdmin === "true");       
let derniereConnexionStr = derniereConnexion === null ? "Jamais connecté" : derniereConnexion;
let nombreConnexionsNombre = Number(nombreConnexions);
console.log("Nom nettoyé :", nomNettoye);
console.log("Âge (nombre) :", ageNombre);
console.log("Email valide :", emailValide);
console.log("Score jeu (nombre) :", scoreJeuNombre);
console.log("Est admin (booléen) :", estAdminBool);
console.log("Dernière connexion :", derniereConnexionStr);
console.log("Nombre connexions (nombre) :", nombreConnexionsNombre);